context("check_poly_formula")

test_that("check poly passed with constants", {
  expect_true(check_poly_formula(y ~ 1))
  expect_true(check_poly_formula(y ~ 0))
  expect_true(check_poly_formula(x ~ 1))
  expect_true(check_poly_formula(x ~ 0))
})

test_that("check poly passed with single explanatory term", {
  expect_true(check_poly_formula(y ~ x))
  expect_true(check_poly_formula(x ~ y))
  expect_true(check_poly_formula(y ~ x - 1))
  expect_true(check_poly_formula(x ~ y - 1))
  expect_true(check_poly_formula(y ~ x + 0))
  expect_true(check_poly_formula(x ~ y + 0))
})

test_that("check test failed with transformed x", {
  expect_true(check_poly_formula(formula = y ~ log(x), check.transf.rhs = FALSE))
  expect_no_warning(
    result <- check_poly_formula(y ~ log(x), warn.transf.rhs.txt = character(0))
  )
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ log(x)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ sqrt(x)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ I(x)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ I(x * 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ I(x / 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ I(x - 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ I(x + 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ I(x^2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ I(x^3)))
  expect_false(result)
})

test_that("check poly passed with x", {
  expect_true(check_poly_formula(y ~ x))
  expect_true(check_poly_formula(y ~ 1 + x))
  expect_true(check_poly_formula(y ~ 0 + x))
  expect_true(check_poly_formula(y ~ -1 + x))
  expect_true(check_poly_formula(y ~ x + 0))
  expect_true(check_poly_formula(y ~ x - 1))
})

test_that("check test failed with transformed y", {
  expect_true(check_poly_formula(formula = log(y) ~ x, check.transf.lhs = FALSE))
  expect_no_warning(
    result <- check_poly_formula(log(y) ~ x, warn.transf.lhs.txt = character(0))
  )
  expect_false(result)
  expect_warning(result <- check_poly_formula(log(y) ~ x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(sqrt(y) ~ x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y - 2 ~ x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y + 2 ~ x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y * 2 ~ x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y / 2 ~ x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(I(y * 2) ~ x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(I(y / 2) ~ y))
  expect_false(result)
  expect_warning(result <- check_poly_formula(I(y - 2) ~ x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(I(y + 2) ~ x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(I(y^2) ~ x))
  expect_false(result)
})

test_that("check poly fails with missing powers", {
  expect_warning(result <- check_poly_formula(y ~ x + I(x^3)))
  expect_false(result)
  expect_true(check_poly_formula(y ~ 1 + x + I(x^2)))
  expect_true(check_poly_formula(y ~ 0 + x + I(x^2)))
  expect_true(check_poly_formula(y ~ -1 + x + I(x^2)))
  expect_true(check_poly_formula(y ~ x + I(x^2) + 0))
  expect_true(check_poly_formula(y ~ x + I(x^2) - 1))
  expect_true(check_poly_formula(y ~ x + I(x^2) + I(x^3)))
  expect_true(check_poly_formula(y ~ x + I(x^2) + I(x^3) + I(x^4)))
  expect_true(check_poly_formula(y ~ I(x) + I(x^2) + I(x^3) + I(x^4)))
})

test_that("check poly passed with increasing powers", {
  expect_true(check_poly_formula(y ~ x + I(x^2)))
  expect_true(check_poly_formula(y ~ 1 + x + I(x^2)))
  expect_true(check_poly_formula(y ~ 0 + x + I(x^2)))
  expect_true(check_poly_formula(y ~ -1 + x + I(x^2)))
  expect_true(check_poly_formula(y ~ x + I(x^2) + 0))
  expect_true(check_poly_formula(y ~ x + I(x^2) - 1))
  expect_true(check_poly_formula(y ~ x + I(x^2) + I(x^3)))
  expect_true(check_poly_formula(y ~ x + I(x^2) + I(x^3) + I(x^4)))
  expect_true(check_poly_formula(y ~ I(x) + I(x^2) + I(x^3) + I(x^4)))
})

test_that("check poly fails with decreasing powers", {
  expect_warning(result <- check_poly_formula(y ~ I(x^2) + x))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ I(x^3) + I(x^2) + x))
  expect_false(result)
  expect_no_warning(result <- check_poly_formula(y ~ I(x^3) + I(x^2) + x,
                                                 warn.incr.poly.text = character(0)))
  expect_false(result)
})

test_that("check poly errors with mixed power and poly", {
  expect_error(check_poly_formula(y ~ I(x^2) + poly(x, 3, raw = TRUE)))
  expect_error(check_poly_formula(y ~ poly(x, 3, raw = TRUE) + I(x^2)))
})

test_that("check poly warns with misisng as is", {
  expect_warning(result <- check_poly_formula(y ~ x + x^2))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 1 + x + x^2))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 0 + x + x^2))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ -1 + x + x^2))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ x + x^2 + I(x^3)))
  expect_false(result)
  expect_no_warning(result <- check_poly_formula(y ~ x + I(x^2) + I(x^3) + x^4))
  expect_true(result)
})

test_that("check poly passed with varied white space", {
  expect_true(check_poly_formula(y~x+I(x^2)))
  expect_true(check_poly_formula(y~x+I(x^2)+I(x^3)))
  expect_true(check_poly_formula(y~x+I(x^2)+I(x^3)+I(x^4)))
  expect_true(check_poly_formula(y  ~  x +  I( x ^ 2)))
})

test_that("check poly passed with poly()", {
  expect_true(check_poly_formula(y ~ poly(x, 2, raw = TRUE)))
  expect_true(check_poly_formula(y ~ 1 + poly(x, 2, raw = TRUE)))
  expect_true(check_poly_formula(y ~ 0 + poly(x, 2, raw = TRUE)))
  expect_true(check_poly_formula(y ~ -1 + poly(x, 2, raw = TRUE)))
  expect_true(check_poly_formula(y ~ poly(x, 4, raw = TRUE)))
})

test_that("check poly gives warning without raw named parameter", {
  expect_warning(result <- check_poly_formula(y ~ poly(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 1 + poly(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 0 + poly(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ -1 + poly(x, 2)))
  expect_false(result)
})

test_that("check bs gives warning", {
  expect_warning(result <- check_poly_formula(y ~ bs(x)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(x ~ bs(y)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ bs(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 1 + bs(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 0 + bs(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ -1 + bs(x, 2)))
  expect_false(result)
})

test_that("check ns gives warning", {
  expect_warning(result <- check_poly_formula(y ~ ns(x)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(x ~ ns(y)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ ns(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 1 + ns(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 0 + ns(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ -1 + ns(x, 2)))
  expect_false(result)
})

test_that("check lspline gives warning", {
  expect_warning(result <- check_poly_formula(y ~ lspline(x)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ qlspline(x)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ elspline(x)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(x ~ lspline(y)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ lspline(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 1 + lspline(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ 0 + lspline(x, 2)))
  expect_false(result)
  expect_warning(result <- check_poly_formula(y ~ -1 + lspline(x, 2)))
  expect_false(result)
})
